# Generated by Django 6.1.1 on 2026-09-19 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AstronautProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astronaut_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Mission Specialist', max_length=50)),
                ('baseline_rxn_ms', models.FloatField(default=280.0)),
                ('baseline_memory_acc', models.FloatField(default=95.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyNeuroCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mean_rxn_ms', models.FloatField()),
                ('rxn_deviation_pct', models.FloatField()),
                ('eeg_condition', models.CharField(max_length=150)),
                ('neuro_health_score', models.IntegerField()),
                ('mission_readiness', models.CharField(max_length=100)),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.astronautprofile')),
            ],
        ),
    ]
